import Head from 'next/head';
import axios from 'axios';
import { useContext } from 'react';
import { Context } from '../context';
import { parseCookies } from 'nookies';

function Protected() {
  const { state } = useContext(Context);
  return (
    <div>
      <Head>
        <title>Firebase with SSR</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h2>Protected page</h2>
      <pre>{JSON.stringify(state, null, 2)}</pre>
    </div>
  );
}

export async function getServerSideProps(context) {
  try {
    const cookies = parseCookies(context);
    const { data } = cookies && await axios.get('http://localhost:8000/api/private-route', {
      headers: {
        token: cookies.token
      }
    });

    if (data.ok) return { props: {} }

    return {
      props: {}
    }
  } catch (err) {
    return {
      redirect: {
        permanent: false,
        destination: '/login'
      }
    }
  }
}

export default Protected;